### ISSUE TITLE
/auth/me broken

### ISSUE THREAD

**Issue by ppvg** [SpoonX/sails-hook-authorization#14]
Calling `/auth/me` causes a `TypeError: Cannot read property 'user' of undefined` at [`AuthController.js:52:34`](https://github.com/SpoonX/sails-hook-authorization/blob/fb9bc142191a3babc08c699f7d70225124dc10be/api/controllers/AuthController.js#L51). It seems the `verifyToken` and `ensureToken` policies are never applied.

**Comment by VMBindraban** [comment]
The policies are applied here https://github.com/SpoonX/sails-hook-authorization/blob/fb9bc142191a3babc08c699f7d70225124dc10be/config/policies.js#L4

**Comment by RWOverdijk** [comment]
@VMBindraban Doesn't answer the ~~question~~ bug.
